apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  template:
    spec:
      containers:
      - name: test-container
        image: titoprime48/chaniprime:latest
        command: ["./server.test", "-test.v"]
      restartPolicy: Never
  backoffLimit: 0