apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  template:
    spec:
      containers:
      - name: test-container
        image: chani-imagen:latest
        command: ["./test-runner"]
      restartPolicy: Never
  backoffLimit: 0